# Generated by Django 3.0.5 on 2020-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('AF', 'Africa'), ('NA', 'North America'), ('OC', 'Oceania'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('SA', 'South America')], default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('on_hand', models.IntegerField()),
                ('price', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
    ]
