# Generated by Django 3.0.5 on 2020-04-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='company_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Company'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(),
        ),
    ]
