# Generated by Django 3.0.5 on 2020-04-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200417_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('on_hand', models.IntegerField()),
                ('price', models.FloatField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Company')),
                ('parts', models.ManyToManyField(to='inventory.Part')),
            ],
        ),
    ]
